
CREATE TABLE UTILIZATORI (
    ID_UTILIZATOR NUMBER(10) PRIMARY KEY,
    NUME_UTILIZATOR VARCHAR2(50) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PAROLA VARCHAR2(100) NOT NULL,
    NUME_COMPLET VARCHAR2(100),
    DATA_NASTERII DATE
);

CREATE TABLE PRODUSE (
    ID_PRODUS NUMBER(10) PRIMARY KEY,
    NUME_PRODUS VARCHAR2(100) NOT NULL,
    PRET NUMBER(10, 2) NOT NULL,
    STOC NUMBER DEFAULT 0,
    ID_CATEGORIE NUMBER,
    FOREIGN KEY (ID_CATEGORIE) REFERENCES CATEGORII(ID_CATEGORIE) ON DELETE SET NULL
);

CREATE TABLE CATEGORII (
    ID_CATEGORIE NUMBER(10) PRIMARY KEY,
    NUME_CATEGORIE VARCHAR2(100) UNIQUE NOT NULL,
    DESCRIERE VARCHAR2(255)
);

CREATE TABLE COMENZI (
    ID_COMANDA NUMBER(10) PRIMARY KEY,
    ID_UTILIZATOR NUMBER NOT NULL,
    DATA_COMANDA DATE DEFAULT SYSDATE,
    TOTAL_PLATA NUMBER(10, 2) DEFAULT 0,
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATORI(ID_UTILIZATOR) ON DELETE CASCADE
);

CREATE TABLE DETALII_COMENZI (
    ID_DETALII_COMANDA NUMBER(10) PRIMARY KEY,
    ID_COMANDA NUMBER NOT NULL,
    ID_PRODUS NUMBER NOT NULL,
    CANTITATE NUMBER DEFAULT 1 CHECK (CANTITATE > 0),
    PRET_PE_UNITATE NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (ID_COMANDA) REFERENCES COMENZI(ID_COMANDA) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS) ON DELETE CASCADE
);

CREATE TABLE FURNIZORI (
    ID_FURNIZOR NUMBER(10) PRIMARY KEY,
    NUME_FURNIZOR VARCHAR2(100) NOT NULL,
    EMAIL_CONTACT VARCHAR2(100) UNIQUE,
    TELEFON VARCHAR2(15),
    ADRESA VARCHAR2(255)
);

CREATE TABLE PRODUSE_FURNIZORI (
    ID_PRODUS_FURNIZOR NUMBER(10) PRIMARY KEY,
    ID_FURNIZOR NUMBER NOT NULL,
    ID_PRODUS NUMBER NOT NULL,
    PRET_FURNIZARE NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (ID_FURNIZOR) REFERENCES FURNIZORI(ID_FURNIZOR) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS) ON DELETE CASCADE
);

CREATE TABLE RECENZII (
    ID_RECENZIE NUMBER(10) PRIMARY KEY,
    ID_UTILIZATOR NUMBER NOT NULL,
    ID_PRODUS NUMBER NOT NULL,
    RATING NUMBER CHECK (RATING BETWEEN 1 AND 5),
    TEXT_RECENZIE VARCHAR2(255),
    DATA_RECENZIE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ID_UTILIZATOR) REFERENCES UTILIZATORI(ID_UTILIZATOR) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS) ON DELETE CASCADE
);

CREATE TABLE REDUCERI (
    ID_REDUCERE NUMBER(10) PRIMARY KEY,
    ID_PRODUS NUMBER NOT NULL,
    PROCENT_REDUCERE NUMBER(5, 2) CHECK (PROCENT_REDUCERE BETWEEN 0 AND 100),
    DATA_INCEPUT DATE NOT NULL,
    DATA_SFARSIT DATE NOT NULL,
    FOREIGN KEY (ID_PRODUS) REFERENCES PRODUSE(ID_PRODUS) ON DELETE CASCADE
);
